### ISSUE TITLE
Existing sitemaps from v4.3 can't be saved after migrating to v5.0

### ISSUE THREAD

**Issue by nolantern** [openhab/openhab-webui#3302]
## The problem
When editing an existing sitemap using the MainUI, saving is not possible. Pressing 'save' does nothing and no feedback appears (like a toast message). Leaving the modified sitemap results in a popup " Changes have not been saved - Do you want to leave this page without saving?".

On the code tab the error "TypeError: t[4].join is not a function" is shown.

<img width="944" height="253" alt="Image" src="https://github.com/user-attachments/assets/dd2b10e4-ee99-4559-b2e4-40332f280f6f" />

<img width="960" height="627" alt="Image" src="https://github.com/user-attachments/assets/d80b7791-7e16-4af4-b7c4-9482fadf3660" />

<img width="304" height="160" alt="Image" src="https://github.com/user-attachments/assets/05ccd6a0-555b-4347-8fdf-62f199aafdce" />

If there are errors like an empty switch widget, a popup appears and asks to save anyway. Pressing "save anyway" does nothing and the popup does not dissapear.
<img width="755" height="189" alt="Image" src="https://github.com/user-attachments/assets/39524bd0-9ffb-440d-9af6-6cca3af89584" />

<details><summary>Here is an sitemap that is affected:</summary>
```
sitemap page_b104d36022 label="Test" {
    Webview height=6 url="/static/weather.html"
    Text icon=switch item=equipTasmotaStromzaehler_chanTasmotaPower label="Spül & Waschmaschine laufen [Gesamtstromverbrauch %.0f %unit%]" valuecolor=[equipTasmotaStromzaehler_chanTasmotaPower<=0="green"] visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch>5 AND Spulmaschine_Stromverbrauch>1 AND DaikinDhwPowerful==OFF] {
        Chart item=Spulmaschine_Stromverbrauch period=h visibility=[Spulmaschine_Stromverbrauch>1]
        Chart item=equipShellyplusplug_e128e719d9_Stromverbrauch period=h visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch>5]
        Switch
    }
    Text icon=switch item=equipTasmotaStromzaehler_chanTasmotaPower label="Spülmaschine läuft [Gesamtstromverbrauch %.0f %unit%]" valuecolor=[equipTasmotaStromzaehler_chanTasmotaPower<=0="green"] visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch<5 AND Spulmaschine_Stromverbrauch>1 AND DaikinDhwPowerful==OFF] {
        Chart item=Spulmaschine_Stromverbrauch period=h
    }
    Text icon=switch item=equipTasmotaStromzaehler_chanTasmotaPower label="Waschmaschine läuft [Gesamtstromverbrauch %.0f %unit%]" valuecolor=[equipTasmotaStromzaehler_chanTasmotaPower<=0="green"] visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch>5 AND Spulmaschine_Stromverbrauch<1 AND DaikinDhwPowerful==OFF] {
        Chart item=equipShellyplusplug_e128e719d9_Stromverbrauch period=h
    }
    Text icon=fire item=equipTasmotaStromzaehler_chanTasmotaPower label="Warmwasser & Waschmaschine laufen [Gesamtstromverbrauch %.0f %unit%]" visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch>5 AND Spulmaschine_Stromverbrauch<1 AND DaikinDhwPowerful==ON]
    Text icon=fire item=equipTasmotaStromzaehler_chanTasmotaPower label="Warmwasser & Spülmaschine laufen [Gesamtstromverbrauch %.0f %unit%]" visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch<5 AND Spulmaschine_Stromverbrauch>1 AND DaikinDhwPowerful==ON]
    Text icon=fire item=equipTasmotaStromzaehler_chanTasmotaPower label="Warmwasser Spül & Waschmaschine laufen [Gesamtstromverbrauch %.0f %unit%]" visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch>5 AND Spulmaschine_Stromverbrauch>1 AND DaikinDhwPowerful==ON]
    Text icon=material:bolt item=equipTasmotaStromzaehler_chanTasmotaPower label="Gesamtstromverbrauch[%.0f %unit%]" valuecolor=[equipTasmotaStromzaehler_chanTasmotaPower<=0="green"] visibility=[equipShellyplusplug_e128e719d9_Stromverbrauch<5 AND Spulmaschine_Stromverbrauch<1] {
        Frame label="Erzeugung" {
            Chart item=pv_sitemap_gruppe label="Leistung Vorhersage" period=PT12H-PT12H service="influxdb"
        }
        Frame label="Verbrauch" {
            Chart item=gruppe_sitemap_stromverbrauch label="Stromverbraucher" period=PT2H
        }
        Frame label="Stromzähler" {
            Chart item=equipTasmotaStromzaehler_chanTasmotaPower period=PT2H
            Text item=equipTasmotaStromzaehler_chanTasmotaTotal_out
            Text item=equipTasmotaStromzaehler_chanTasmotaTotal_in
        }
    }
    Text icon=material:videogame_asset label="Büro" {
        Text icon=screen-on label="PC [online]" visibility=[NetworkBindingFelixPC==ON]
        Text icon=screen-off label="PC [offline]" visibility=[NetworkBindingFelixPC==OFF] {
            Switch icon=screen-off item=BtnWakeOnLanFelixPC label="Computer [offline]" mappings=[ON="Wake On Lan"] visibility=[NetworkBindingFelixPC==OFF]
            Text icon=screen-on label="PC [online]" visibility=[NetworkBindingFelixPC==ON]
        }
        Slider item=BuroAmbi_Helligkeit label="Helligkeit" maxValue=100 minValue=0 switchSupport
        Slider icon=heating item=BuroGruppeFarbtemperatur label="Farbtemperatur" maxValue=100 minValue=0
        Setpoint icon=rollershutter item=RolloBuro label="Rollo"
        Colortemperaturepicker item=BuroAmbi_Farbtemperatur label="Farbtemperatur" maxValue=5500 minValue=2800
    }
    Text icon=material:weekend label="Wohnzimmer" {
        Slider icon=light item=WohnzimmerGruppeDeckeHelligkeit label="Decken Licht" switchSupport
        Slider icon=light item=WohnzimmerGruppeSchrankwandHelligkeit label="Ambi Licht" switchSupport
        Slider icon=screen item=TvHelligkeit label="TV Beleuchtung" maxValue=50
        Slider icon=heating item=WohnzimmerGruppeFarbtemperatur label="Wärme" switchSupport
        Text icon=none label="Rollläden"
        Setpoint item=GruppeBlindsWohnEss label="Wohnzimmer"
        Setpoint icon=rollershutter item=RolloEsszimmer label="Esstisch"
        Setpoint item=RolloWohnenFest label="Sofa"
        Setpoint icon=rollershutter item=RolloWohnenTur label="TV Wand"
    }
    Text icon=material:roller_shades label="Rollos" {
        Frame {
            Text icon=material:air iconcolor=["maroon"] label="Achtung Sturmgefahr" visibility=[One_Call_API__Lokales_Wetter_und_Wettervorhersage_Current_Windspeed >=40, One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastToday_Windspeed >=40, One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastHours01_Windspeed >=40]
            Setpoint icon=material:weekend item=GruppeBlindsWohnEss label="Wohnzimmer"
            Setpoint icon=material:flatware item=GruppeRolloKuche label="Küche"
        }
        Frame label="Erdgeschoss" {
            Setpoint item=RolloWohnenFest
            Setpoint item=RolloWohnenTur
            Setpoint item=RolloEsszimmer
            Setpoint item=RolloKucheGarten
            Setpoint item=RolloKucheGarage
            Setpoint item=RolloBuro
            Setpoint item=RolloWc
        }
        Frame label="Dachgeschoss" {
            Setpoint item=RolloSchlafzimmer
            Setpoint item=RolloKindGarten
            Setpoint item=RolloKindStrasse
            Setpoint item=RolloBad
        }
        Frame label="Einstellungen" {
            Switch iconcolor=[OFF="grey", ON="green"] icon=[ON="material:brightness_auto", OFF="switch"] item=cloudingEnabled
        }
    }
    Switch icon=Garagedoor-ajar item=GaragentorStartStop label="Garagentor offen" labelcolor=["orange"] mappings=[ON="Start/Stop"] visibility=[GaragentorGeschlossen==OFF]
    Switch icon=Garagedoor-closed item=GaragentorStartStop label="Garagentor geschlossen" mappings=[ON="Start/Stop"] visibility=[GaragentorGeschlossen==ON]
    Switch icon=light item=shellyplusplugse465b8b55b38__19216817923_Betrieb label="Galerie Beleuchtung" visibility=[astroSunPhase!=DAYLIGHT, astroSunPhase==DAYLIGHT AND shellyplusplugse465b8b55b38__19216817923_Betrieb==ON]
    Switch icon=moon item=itmRuleTrigger label="Schlafposition" mappings=[scnRolloSchlafNacht=Aktivieren] visibility=[RolloSchlafzimmer<70 AND astroSunPhase!=DAYLIGHT]
    Text icon=material:thermostat label="Heizung" {
        Frame {
            Text icon=snow iconcolor=["aqua"] item=One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastTomorrow_Mintemperature label="Frostwarnung für morgen [%.1f°C]" labelcolor=["aqua"] valuecolor=["aqua"] visibility=[One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastTomorrow_Mintemperature<=1]
        }
        Frame label="Stromverbrauch" {
            Text item=equipTasmotaStromzaehler_chanTasmotaPower label="⚡ Gesamt Verbrauch (Haus)" labelcolor=[<100="yellow", <500="orange", <1000="red", >=1000="maroon"] valuecolor=[<100="yellow", <500="orange", <1000="red", >=1000="maroon"] visibility=[equipTasmotaStromzaehler_chanTasmotaPower>=0] {
                Chart item=equipTasmotaStromzaehler_chanTasmotaPower label="Stromverbrauch" period=h
                Chart item=gruppe_sitemap_stromverbrauch label="Stromverbraucher" period=PT2H
                Chart item=SungrowInverterTotalActivePower label="PV" period=h
                Text item=pvForecastSiteTomorrowEnergy label="PV Vorhersage für Morgen [%.1f kWh]"
            }
            Text item=equipTasmotaStromzaehler_chanTasmotaPower label="⚡ Gesamt Überschuss 🌞" labelcolor=[<"-1000"="lime", <"-0"="green"] valuecolor=[<"-1000"="lime", <"-0"="green"] visibility=[equipTasmotaStromzaehler_chanTasmotaPower<0] {
                Chart item=equipTasmotaStromzaehler_chanTasmotaPower label="Stromverbrauch" period=h
                Chart item=gruppe_sitemap_stromverbrauch label="Stromverbraucher" period=PT2H
                Chart item=SungrowInverterTotalActivePower label="PV" period=h
                Text item=pvForecastSiteTomorrowEnergy label="PV Vorhersage für Morgen [%.1f kWh]"
            }
            Text item=itmESPAltherma_InvPwr label="⚡ Heizung Verbrauch" labelcolor=[0="white", <100="lime", <200="green", <500="yellow", <1000="orange", <1500="red", >=1500="maroon"] valuecolor=[0="white", <100="lime", <200="green", <500="yellow", <1000="orange", <1500="red", >=1500="maroon"] {
                Text item=ESPAltherma_Durchflussmenge label="Durchflussmenge Pumpe"
                Text item=equipESPAltherma_Heizungsvorlauf_Solltemperatur label="Vorlauf Soll"
                Text item=HeizungVorlaufTempIst label="Vorlauf Ist"
            }
        }
        Frame label="Wärmepumpen Limit" {
            Switch item=AutoWpPowerLimit label="Auto Stromverbrauch Regelung"
            Switch item=equipESPAltherma_EspAltherma_Smart_Grid label="Betrieb[]" mappings=[1=Blockiert, 0=Freigegeben] visibility=[AutoWpPowerLimit==OFF]
            Selection item=equipESPAltherma_EspAltherma_Power_Limit visibility=[equipESPAltherma_EspAltherma_Smart_Grid!=1 AND AutoWpPowerLimit!=ON]
            Text icon=none label="Erweitert" {
                Text item=equipTasmotaStromzaehler_chanTasmotaPower
                Text item=itmESPAltherma_InvPwr
                Selection item=equipESPAltherma_EspAltherma_Smart_Grid label="Smart Grid Modus"
                Switch item=AutoWpPowerLimit
                Selection item=equipESPAltherma_EspAltherma_Power_Limit
            }
        }
        Frame label="Fußbodenheizung" {
            Switch iconcolor=[equipESPAltherma_Raumheizbetrieb==OFF="grey"] icon=[AutoWpRoomheating==OFF="none", DaikinHeizungHauptschalter!=ON="none", AutoWpRoomheating==ON="switch"] item=AutoWpRoomheating
            Switch iconcolor=[equipESPAltherma_Raumheizbetrieb==OFF="grey"] icon=[==ON="switch", !=ON="none"] item=DaikinHeizungHauptschalter label="Hauptschalter" visibility=[AutoWpRoomheating!=ON]
            Text item=innenAussenTempString label="Temperaturen [%s]"
            Text icon=none label="Erweitert" {
                Frame label="Fußbodenheizung" {
                    Text icon=none item=Aussentemperatur label="🏡 Außentemperatur"
                    Text icon=none item=itmShellyPlusHT_Temperatur label="🛋 Innentemperatur"
                    Text item=equipESPAltherma_Raumheizbetrieb valuecolor=[==ON="green"]
                    Text item=equipESPAltherma_Espaltherma_5FDHW_Switch valuecolor=[==ON="green"]
                    Switch iconcolor=[==ON="aqua", ==OFF="grey"] icon=[==ON="snow", ==OFF="switch"] item=FrostschutzNachrichtSchalter label="Frostwarnung"
                }
                Frame label="Vorlauftemperatur" {
                    Text item=HeizungVorlaufTempIst label="Aktuell"
                    Text item=equipESPAltherma_Heizungsvorlauf_Solltemperatur label="Ziel"
                    Slider item=HeizungOffset maxValue=10 minValue=-10 releaseOnly
                    Setpoint item=HeizungOffset label="Wärmer/Kälter[%.1f °C]" maxValue=10 minValue=-10
                }
                Frame label="Pumpe" {
                    Text item=ESPAltherma_Durchflussmenge label="Durchflussmenge"
                }
                Frame label="Auto Betrieb: Tagsüber Heizen" {
                    Text item=One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastToday_Mintemperature
                    Text item=One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastTomorrow_Mintemperature
                    Text icon=none label="Wenn Nachts kälter als:"
                    Slider item=heatpumpTransitionThreshold label="[%.0f °C]" maxValue=20 minValue=-20 releaseOnly
                }
                Frame label="Auto Betrieb: Tag & Nacht Heizen" {
                    Text item=One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastToday_Maxtemperature
                    Text item=One_Call_API__Lokales_Wetter_und_Wettervorhersage_ForecastTomorrow_Maxtemperature
                    Text icon=none label="Wenn Tag & Nacht kälter als:"
                    Slider item=heatpumpWinterThreshold label="[%.0f °C]" maxValue=20 minValue=-20 releaseOnly
                }
            }
        }
        Frame label="Warmwasser" {
            Switch iconcolor=[equipESPAltherma_Espaltherma_5FDHW_Switch==OFF="grey"] icon=[AutoWpDhw==OFF="none", WarmwasserHauptschalter!=ON="none", AutoWpDhw==ON="switch"] item=AutoWpDhw
            Switch iconcolor=[equipESPAltherma_Espaltherma_5FDHW_Switch==OFF="grey"] icon=[WarmwasserHauptschalter!=ON="none"] item=WarmwasserHauptschalter label="Hauptschalter" visibility=[AutoWpDhw!=ON]
            Text icon=none item=DaikinDhwTempIst label="Temperatur [🛁 %.1f °C]"
            Buttongrid buttons=[1:1:ruleAlthermaHotWaterNow="Wasser jetzt einmalig erwärmen"] item=itmRuleTrigger visibility=[DaikinDhwTempIst<60 AND DaikinDhwPowerful!=ON]
            Text icon=none label="Erweitert" {
                Frame label="Warmwasser Status" {
                    Text item=equipESPAltherma_Raumheizbetrieb valuecolor=[==ON="green"]
                    Text item=equipESPAltherma_Espaltherma_5FDHW_Switch valuecolor=[==ON="green", ==OFF="red"]
                    Chart item=DaikinDhwTempIst period=4h
                    Text icon=none item=DaikinDhwTempIst label="Aktuell [%.1f °C]"
                    Text item=HeizungVorlaufTempIst label="Vorlauf Ist [%.1f °C]"
                    Text item=ESPAltherma_Durchflussmenge
                }
                Frame label="Einmalige Einstellungen" {
                    Slider icon=none item=DhwSetpoint label="Aktuelle Zieltemperatur [%.1f °C]" maxValue=70 minValue=30
                    Switch item=DaikinDhwPowerful label="Leistungsmodus"
                    Buttongrid buttons=[1:1:ruleAlthermaHotWaterNow=Einmalig_auf_Obergrenze_erwaermen] item=itmRuleTrigger
                }
                Frame label="Dauerhafte Einstellungen" {
                    Setpoint item=pxWarmWasserMax label="Obergrenze [%.1f °C]" maxValue=70 minValue=25
                    Setpoint item=pxWarmWasserMin label="Untergrenze [%.1f °C]" maxValue=60 minValue=25
                }
            }
        }
    }
    Text icon=[KlingelHauptschalter==OFF="material:notifications_off", KlingelHauptschalter==ON="material:notifications_active"] label="Klingel" {
        Switch icon=[==OFF="material:notifications_off", ==ON="material:notifications_active"] item=KlingelHauptschalter label="Klinkel"
        Switch icon=[==OFF="material:alarm_off", ==ON="material:alarm_on"] item=KlingelAutomatischDeaktivieren
    }
}
```
</details>

<details><summary>Here is an sitemap that is not affected:</summary>
```
sitemap 3dprint_sitemap label="3D Print" {
    Text item=3dp_power label="Leistung [%.0f %unit%]"
    Text item=3dp_energy label="Energieverbrauch [%.0f %unit%]"
    Text item=3dp_switch label="Hauptschalter" {
        Switch item=3dp_switch
    }
}
```
</details>

## Expected behavior

When I edit a sitemap using MainUI I can save it. Even if there are errors, it appears a popup which asks to save anyway. Pressing "save anyway" saves the sitemap and closes the popup.

## Steps to reproduce

Edit Sitemaps created in 4.3 in 5.0.0 and try to save.

## Your environment

```yaml
runtimeInfo:
  version: 5.0.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 21.0.8
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu21.44+17-CA
  osName: Linux
  osVersion: 5.15.0-1079-raspi
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 43698552
  totalMemory: 543162368
  uptime: 88053
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-icalendar
  - binding-ipcamera
  - binding-modbus
  - binding-mqtt
  - binding-network
  - binding-openweathermap
  - binding-shelly
  - binding-solarforecast
  - binding-tibber
  - binding-tradfri
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en
    languages:
      - en
      - de
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:141.0) Gecko/20100101
    Firefox/141.0
timestamp: 2025-07-27T19:36:58.970Z

```

## Browser console

```txt
TypeError: cyclic object value
    preProcessSitemapSave https://192.168.178.56:8444/js/app.a8d59c3143efa2b54661.js:1
    save https://192.168.178.56:8444/js/app.a8d59c3143efa2b54661.js:1
    click https://192.168.178.56:8444/js/app.a8d59c3143efa2b54661.js:1
    Kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    n https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    Kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    $emit https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    r https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    r https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    dispatchEvent https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    onClick https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    mounted https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    Kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    insert https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    S https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    Mi https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    _update https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    r https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    get https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    run https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    jn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    sr https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    nr https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    promise callback*Zn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    sr https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    In https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    update https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    notify https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    62893 https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    pageComponentLoader https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    load https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    t https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    async https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    promise callback*async https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    b https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    navigate https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    a https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    t https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    w https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    b https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    t https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    w https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    a https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    k https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    navigate https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    click https://192.168.178.56:8444/js/app.a8d59c3143efa2b54661.js:1
    click https://192.168.178.56:8444/js/app.a8d59c3143efa2b54661.js:1
    click https://192.168.178.56:8444/js/app.a8d59c3143efa2b54661.js:1
    Kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    n https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    Kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    $emit https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    r https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    r https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    dispatchEvent https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    onClick https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    mounted https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    Kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    kn https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    insert https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    S https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
    Mi https://192.168.178.56:8444/js/app.69aed1c1b8f99b083ac7.js:2
app.69aed1c1b8f99b083ac7.js:2:1536012

```

## Additional information
Tested in Firefox 141.0 (64-Bit) and openHAB Android App 3.17.2
No relevant information is logged (level info) in openHAB console.
