### ISSUE TITLE
oh-input throws TypeError: this.getVariableScope is not a function in openHAB 5.1.1 when used with oh-context variables (worked in 5.0.3)

### ISSUE THREAD

**Issue by mannemiethe** [openhab/openhab-webui#3755]
## The problem

After upgrading to openHAB 5.1.1, an oh-input of type time nested inside oh-context fails to load after a page refresh or initial load. The widget worked as expected in openHAB 5.0.3. In 5.1.1, it throws a runtime exception referencing getVariableScope, causing the input to break.

`TypeError: this.getVariableScope is not a function
    at Proxy.value (index-D8m6Kk7Q.js:43504:25)
    at nt (index-D8m6Kk7Q.js:372:19)
    at get value (index-D8m6Kk7Q.js:930:14)
    at Object.get [as value] (index-D8m6Kk7Q.js:1658:23)
    at Object.get (index-D8m6Kk7Q.js:1599:22)
    at Proxy.valueForDatepicker (index-D8m6Kk7Q.js:43554:37)
    at nt (index-D8m6Kk7Q.js:372:19)
    at get value (index-D8m6Kk7Q.js:930:14)
    at Object.get [as valueForDatepicker] (index-D8m6Kk7Q.js:1658:23)
    at index-D8m6Kk7Q.js:43650:86`

<img width="876" height="171" alt="Image" src="https://github.com/user-attachments/assets/73970954-853f-45f5-964c-95556afbd005" />

## Expected behavior

variable should be used

## Steps to reproduce

1. Create a new Widget in 5..1.1 and insert this: after refresh or reload the problem is in the console
 
uid: oh-input-test
props:
  parameters: []
  parameterGroups: []
timestamp: Jan 12, 2026, 11:40:43 PM
component: oh-context
config:
  variables:
    editData:
      time: ""
slots:
  default:
    - component: oh-input
      config:
        type: time
        value: =vars.editTime || 12:00
        variable: editData
        variableKey: time
        inputStyle: text
        style:
          font-size: 20px
          padding: 8px
          width: 100%
          background: "=themeOptions.dark === 'dark' ? 'rgba(255,255,255,0.1)' :
            'rgba(0,0,0,0.08)'"
          border-radius: 6px
          border: none
          color: "=themeOptions.dark === 'dark' ? '#fff' : '#000'"
          color-scheme: "=themeOptions.dark === 'dark' ? 'dark' : 'light'"

## Your environment

```yaml

```
docker and openhab
## Browser console

```txt

```
