### PR TITLE
useStatesStore: Fix error in expression tester with =items formula

### LINKED ISSUE #3876: Expression-tester crashes with items object return value
This looks like a regressions from #3749 

If the final result of the expression in the expression tester is just the `items` object then the expression tester fails to render with an error of:

```
index-CVHPjz-J.js:1217 TypeError: _a.toString is not a function
    at Proxy.result (developer-dock-Cqc192gQ.js:2013:100)
    at ot (index-CVHPjz-J.js:380:19)
    at get value (index-CVHPjz-J.js:994:14)
    at Object.get [as result] (index-CVHPjz-J.js:2436:23)
    at developer-dock-Cqc192gQ.js:2049:12
    at r2 (index-CVHPjz-J.js:1311:14)
    at R (index-CVHPjz-J.js:2270:23)
    at Proxy.vg (index-CVHPjz-J.js:12863:7)
    at go (index-CVHPjz-J.js:2713:20)
    at Xe.s3 [as fn] (index-CVHPjz-J.js:3083:20)
```

This is true with both the simplest of forms:

```
=items
```

and more complex expressions:

```
=(1 == 2)?("True"):(items)
```

### PR DESCRIPTION
**Pull request by jsjames**
Fixes #3876

Adds `toString()` function to `trackedItems` proxy.

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]

**Comment by BrettLHolmes** [comment]
@jsjames  by the looks of things this was merged into 5.1.3 -

Was this the same issue with the developer tools and the Widgets Expression Tester?

 if so I loaded 5.1.3 this morning and the issue is still there or did I assume wrong and its not part of 5.1.3

**Comment by florian-h05** [comment]
The widget expression tester is part of the developer tools, what distinction do you make here? Please reload Main UI and clear cache through the about page.

**Comment by BrettLHolmes** [comment]
> The widget expression tester is part of the developer tools, what distinction do you make here? Please reload Main UI and clear cache through the about page.

Hi @florian-h05  when i use the Developer sidebar to show the current status of an item i get [object Object] rarther than the current status

Here are two screenshots from a  5.1.2/5.1.3 and a 5.0.3 system
image
image

PS i did reload the App from the About Menu and its the same.

**Comment by jsjames** [comment]
That is an unrelated issue to what this PR fixed. This PR fixed a exception that occurred when just referring to "=items". I would submit a new issue regarding this that we can track and assess.

**Comment by BrettLHolmes** [comment]
> That is an unrelated issue to what this PR fixed. This PR fixed a exception that occurred when just referring to "=items". I would submit a new issue regarding this that we can track and assess.

Will do thanks

**Comment by florian-h05** [comment]
I've also noticed this, but it is totally unrelated to what has been fixed here. I will get it back working though.

**Comment by florian-h05** [comment]
@BrettLHolmes Please don't create an issue if you haven't done so yet, I have a PR: #3920
