### ISSUE TITLE
Expression-tester crashes with items object return value

### ISSUE THREAD

**Issue by JustinGeorgi** [openhab/openhab-webui#3876]
This looks like a regressions from #3749 

If the final result of the expression in the expression tester is just the `items` object then the expression tester fails to render with an error of:

```
index-CVHPjz-J.js:1217 TypeError: _a.toString is not a function
    at Proxy.result (developer-dock-Cqc192gQ.js:2013:100)
    at ot (index-CVHPjz-J.js:380:19)
    at get value (index-CVHPjz-J.js:994:14)
    at Object.get [as result] (index-CVHPjz-J.js:2436:23)
    at developer-dock-Cqc192gQ.js:2049:12
    at r2 (index-CVHPjz-J.js:1311:14)
    at R (index-CVHPjz-J.js:2270:23)
    at Proxy.vg (index-CVHPjz-J.js:12863:7)
    at go (index-CVHPjz-J.js:2713:20)
    at Xe.s3 [as fn] (index-CVHPjz-J.js:3083:20)
```

This is true with both the simplest of forms:

```
=items
```

and more complex expressions:

```
=(1 == 2)?("True"):(items)
```
